---
- name: This is a recipe for how to run packit tests
  hosts: all
  tasks:
    - include_tasks: tasks/project-dir.yaml
    - include_tasks: tasks/rpm-test-deps.yaml
    - include_tasks: tasks/install-packit.yaml
    - include_tasks: tasks/sandcastle.yaml
    - name: Run session recorded tests
      # uncomment once https://github.com/packit/requre/issues/145 is resolved
      #      environment:
      #        REQURE_MODE: read
      command: make check TEST_TARGET=tests_recording
      args:
        chdir: "{{ project_dir }}"
